#pragma once

#define STREAMDECK_INPUT_REPORT_SIZE   512u
#define STREAMDECK_OUTPUT_REPORT_SIZE 1024u
#define STREAMDECK_FEATURE_REPORT_SIZE  32u
#define STREAMDECK_RING_CAPACITY       128u

#define MIRAGE_CAPTURE_NONE     0u
#define MIRAGE_CAPTURE_OUTPUT   1u
#define MIRAGE_CAPTURE_FEATURE  2u

#define IOCTL_MIRAGE_INJECT_INPUT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_MIRAGE_GET_CAPTURE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_READ_DATA)

#include <pshpack1.h>
typedef struct _MIRAGE_CAPTURED_REPORT {
    UCHAR Kind;
    UCHAR Reserved;
    USHORT Length;
    UCHAR Data[STREAMDECK_OUTPUT_REPORT_SIZE];
} MIRAGE_CAPTURED_REPORT, *PMIRAGE_CAPTURED_REPORT;
#include <poppack.h>
