#pragma once

#define N4PRO_INPUT_REPORT_SIZE  512u
#define N4PRO_OUTPUT_REPORT_SIZE 1024u
#define N4PRO_HID_INPUT_REPORT_SIZE  (N4PRO_INPUT_REPORT_SIZE + 1u)
#define N4PRO_HID_OUTPUT_REPORT_SIZE (N4PRO_OUTPUT_REPORT_SIZE + 1u)
#define N4PRO_RING_CAPACITY      128u

#define N4PRO_SIDE_REPORT_ID     0u
#define N4PRO_SIDE_MAGIC         0x4556424Du /* "MBVE" as little endian */
#define N4PRO_SIDE_INJECT_INPUT  1u
#define N4PRO_SIDE_OUTPUT_PACKET 2u
#define N4PRO_SIDE_NO_PACKET     3u
#define N4PRO_DIAGNOSTIC_MAGIC   0x47414944u /* "DIAG" as little endian */

#include <pshpack1.h>
typedef struct _N4PRO_SIDE_REPORT {
    ULONG Magic;
    UCHAR Command;
    ULONG Sequence;
    UCHAR Data[N4PRO_OUTPUT_REPORT_SIZE];
} N4PRO_SIDE_REPORT, *PN4PRO_SIDE_REPORT;
#include <poppack.h>

#define N4PRO_FEATURE_PAYLOAD_SIZE ((USHORT)sizeof(N4PRO_SIDE_REPORT))
#define N4PRO_FEATURE_REPORT_SIZE  (N4PRO_FEATURE_PAYLOAD_SIZE + 1u)
