#pragma once

#define STREAMDECK_INPUT_REPORT_SIZE   512u
#define STREAMDECK_OUTPUT_REPORT_SIZE 1024u
#define STREAMDECK_FEATURE_REPORT_SIZE  32u
#define STREAMDECK_RING_CAPACITY       128u

#define MIRAGE_PANEL_REPORT_ID       0x0Bu
#define MIRAGE_PANEL_HEADER_SIZE       13u
#define MIRAGE_PANEL_PAYLOAD_SIZE \
    (STREAMDECK_FEATURE_REPORT_SIZE - MIRAGE_PANEL_HEADER_SIZE)

#define MIRAGE_PANEL_COMMAND_NONE           0u
#define MIRAGE_PANEL_COMMAND_INJECT_CHUNK   1u
#define MIRAGE_PANEL_COMMAND_RESET          2u
#define MIRAGE_PANEL_COMMAND_CAPTURE_CHUNK  3u

#define MIRAGE_CAPTURE_NONE     0u
#define MIRAGE_CAPTURE_OUTPUT   1u
#define MIRAGE_CAPTURE_FEATURE  2u

#include <pshpack1.h>
typedef struct _MIRAGE_CAPTURED_REPORT {
    UCHAR Kind;
    UCHAR Reserved;
    USHORT Length;
    UCHAR Data[STREAMDECK_OUTPUT_REPORT_SIZE];
} MIRAGE_CAPTURED_REPORT, *PMIRAGE_CAPTURED_REPORT;
#include <poppack.h>
